# Monty Standards Configuration
# Machine-readable config for AI agents and tools

# Project metadata
name: my-project
description: My project description
version: 0.1.0

# Language and tooling
language: node  # node | python
versioning: semver  # semver | none (default: semver)

# ============================================================
# RULES (MUST FOLLOW)
# ============================================================
# These are hard requirements. Breaking these will cause
# bugs, security issues, or data corruption.
# Individual repos CANNOT override rules without documenting why.
rules:
  node:
    - name: error-handling
      description: All async operations must handle errors
      rationale: Unhandled errors cause silent failures and data corruption
      enforcement: lint-error
    - name: no-sync-io
      description: Do not use synchronous I/O operations
      rationale: Blocks event loop, causes performance issues
      enforcement: lint-error
    - name: input-validation
      description: Validate all external input
      rationale: Prevents injection attacks and data corruption
      enforcement: code-review
    - name: no-eval
      description: Never use eval() or similar code execution
      rationale: Security vulnerability
      enforcement: lint-error
    - name: record-in-github
      description: Record decisions and discussions in GitHub issues/PRs
      rationale: Preserves institutional knowledge for future contributors
      enforcement: code-review
  python:
    - name: no-mutable-defaults
      description: Do not use mutable default arguments
      rationale: Causes subtle bugs with shared state
      enforcement: lint-error
    - name: input-validation
      description: Validate all external input
      rationale: Prevents injection attacks and data corruption
      enforcement: code-review
    - name: no-bare-except
      description: Do not catch Exception without specific type
      rationale: Hides bugs and makes debugging harder
      enforcement: lint-error
    - name: record-in-github
      description: Record decisions and discussions in GitHub issues/PRs
      rationale: Preserves institutional knowledge for future contributors
      enforcement: code-review

# ============================================================
# GUIDANCE (SHOULD FOLLOW)
# ============================================================
# These are recommendations. Breaking these will cause
# maintainability issues, technical debt, or bugs.
# Individual repos can override with justification.
guidance:
  node:
    - name: async-await
      description: Prefer async/await over callbacks
      rationale: Better readability and error handling
    - name: type-annotations
      description: Use JSDoc or TypeScript for type safety
      rationale: Catches errors at compile time
    - name: repository-pattern
      description: Use repository pattern for data access
      rationale: Separates concerns, easier testing
    - name: service-layer
      description: Business logic in services, not handlers
      rationale: Reusable, testable business logic
    - name: short-functions
      description: Keep functions under 30 lines
      rationale: Improves readability and testability
    - name: single-responsibility
      description: Each module/class has one purpose
      rationale: Easier to understand and maintain
  python:
    - name: type-hints
      description: Add type hints to all functions
      rationale: Self-documenting code, better IDE support
    - name: dataclass
      description: Use dataclasses for simple data objects
      rationale: Boilerplate reduction, type safety
    - name: context-manager
      description: Use with statements for resources
      rationale: Prevents resource leaks
    - name: abstract-base-class
      description: Use ABCs for interfaces
      rationale: Clear contracts, polymorphism
    - name: short-functions
      description: Keep functions under 50 lines
      rationale: Improves readability and testability
    - name: single-responsibility
      description: Each function/class has one purpose
      rationale: Easier to understand and maintain

# ============================================================
# OVERRIDES (Documented Exceptions)
# ============================================================
# Individual repos can override rules/guidance.
# All overrides MUST be documented here with rationale.
overrides: []
# Example:
# - rule: no-mutable-defaults
#   override: true
#   rationale: "Using functools.lru_cache requires mutable defaults"
#   approved-by: tech-lead
#   date: 2026-02-04

# Conventional commits configuration
commits:
  types:
    - feat
    - fix
    - docs
    - refactor
    - test
    - ci
    - chore
  scopes:
    required: false

# Version bump rules (when versioning is enabled)
versioning:
  major_triggers:
    - "BREAKING CHANGE"
    - "feat!:"
  minor_triggers:
    - "feat:"
  patch_triggers:
    - "fix:"
    - "refactor:"
    - "docs:"

# Testing requirements
testing:
  coverage_min: 80

# Documentation requirements
docs:
  required:
    - README.md
    - LICENSE
  recommended:
    - CONTRIBUTING.md
    - CHANGELOG.md
