# Monty Standards Configuration
# Machine-readable config for AI agents and tools

# Project metadata
name: my-project
description: My project description
version: 0.1.0

# Language and tooling
language: node  # node | python
versioning: semver  # semver | calver | none (default: semver)

# Design patterns by language
patterns:
  node:
    - name: repository
      description: Use repository pattern for data access
      example: |
        // src/repositories/user.repository.js
        export class UserRepository {
          constructor(db) { this.db = db }
          async findById(id) { return this.db.users.find(id) }
        }
    - name: factory
      description: Use factory pattern for test fixtures
    - name: service-layer
      description: Business logic in services, not handlers
  python:
    - name: dataclass
      description: Use dataclasses for DTOs and simple objects
    - name: context-manager
      description: Use context managers for resource handling
    - name: abstract-base-class
      description: Use ABCs for interfaces and contracts

# Anti-patterns to avoid (see docs/ANTI_PATTERNS_PROPOSAL.md for details)
anti_patterns:
  node:
    - name: callback-hell
      description: Nested callbacks make code hard to read
      instead: Use async/await or Promises
      severity: error
    - name: unhandled-errors
      description: Not catching promise rejections or errors
      instead: Always handle or propagate errors
      severity: error
    - name: sync-io
      description: Using synchronous I/O operations
      instead: Use async/await with fs.promises
      severity: error
    - name: god-object
      description: Single class/module with too many responsibilities
      instead: Split into focused units
      severity: warning
    - name: implicit-any
      description: Missing type annotations
      instead: Use JSDoc or TypeScript
      severity: warning
  python:
    - name: mutable-defaults
      description: Using mutable defaults in function signatures
      instead: Use None as default and initialize inside
      severity: error
    - name: wildcard-imports
      description: from module import *
      instead: Import specific symbols
      severity: warning
    - name: missing-type-hints
      description: Functions without type annotations
      instead: Add type hints to all functions
      severity: warning
    - name: bare-except
      description: Catching Exception without specific type
      instead: Catch specific exception types
      severity: error
    - name: no-context-manager
      description: Not using with statement for resources
      instead: Use context managers for file/db/network
      severity: warning

# Conventional commits configuration
commits:
  types:
    - feat
    - fix
    - docs
    - refactor
    - test
    - ci
    - chore
  scopes:
    required: false

# Version bump rules (when versioning is enabled)
versioning:
  major_triggers:
    - "BREAKING CHANGE"
    - "feat!:"
  minor_triggers:
    - "feat:"
  patch_triggers:
    - "fix:"
    - "refactor:"
    - "docs:"

# Testing requirements
testing:
  coverage_min: 80

# Documentation requirements
docs:
  required:
    - README.md
    - LICENSE
  recommended:
    - CONTRIBUTING.md
    - CHANGELOG.md
